# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='bak_data',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='tags',
            name='desc',
            field=models.CharField(default='', max_length=256),
        ),
    ]
