# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0005_auto_20170215_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
    ]
