# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0006_videos_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='bak_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='bak_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5173\u952e\u5b57(\u7528\u82f1\u6587\u72b6\u6001\u4e0b\u9017\u53f7\u5206\u9694)'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pic_url',
            field=models.FileField(upload_to='F:\\pythonCode\\lxdzx/static/files//recv/', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='\u7f29\u7565\u56fe'),
        ),
    ]
