# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_manager', '0010_auto_20170228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
